### root
GET http://localhost:8888/

###
GET http://localhost:8888/auth/login

###
POST http://localhost:8888/auth/logout
Authorization: Bearer NskiarhF9Dl14buvsVgdZTdGVwuQLA

###
GET http://localhost:8888/auth/user
Authorization: Bearer NskiarhF9Dl14buvsVgdZTdGVwuQLA